import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  development: [
    { type: "autogenerated", dirName: "." },
    {
      type: "link",
      href: "/development/rest-api",
      label: "Rest API",
    },
  ],
};

export default sidebars;
