import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// https://docusaurus.io/docs/sidebar
const sidebars: SidebarsConfig = {
  guidesSidebar: [{ type: "autogenerated", dirName: "guides" }],
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
