import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import openapiSidebar from "./docs/api/openapi/sidebar";

// https://docusaurus.io/docs/sidebar
const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: "autogenerated",
      dirName: "guides",
    },
  ],
  apiSidebar: [
    {
      type: "doc",
      id: "api/api-key/index",
    },
    {
      type: "category",
      label: "Rest API",
      link: {
        type: "generated-index",
        title: "Rest API",
        description: "xxxx",
        slug: "/category/rest-api",
      },
      items: openapiSidebar,
      collapsed: false,
      collapsible: true,
    },
  ],
};

export default sidebars;
