import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  development: [
    { type: "autogenerated", dirName: "." },
    {
      type: "category",
      label: "Rest API",
      items: [
        {
          type: "link",
          href: "/development/rest-api/swagger-ui",
          label: "Swagger UI",
        },
        {
          type: "link",
          href: "/development/rest-api/stoplight-elements",
          label: "Stoplight Elements",
        },
      ],
    },
  ],
};

export default sidebars;
